### ISSUE TITLE
Unable to access the database

### ISSUE THREAD

**Issue by walterzenia** [Asif-Abrar/Bank_Management_System#1]
I having difficulty accessing the database. When i try to open the APP_DATA, i am prompted with error that BMS-2019122105540 because its version is 852. This server version supports 782 and earlier. A downgrade path is not supported. 
Could not open a new database aspnet BMS-2019122105540. CREATE DATABASE is aborted. 
what should i do?
Sorry for disturbance

**Comment by Asif-Abrar** [comment]
You have to create your own database. I did this project 3 years ago. So there's a lot of things changed since then. You can get the basic idea of an ASP.NET project structure from here. But If you try to copy the whole project and run then you have to change a lot of things. Its better if you learn ASP.NET from any documentation or tutorial first and then try to create your own. Also you're getting the idea of structure from this project. Things will be easy for you.
